CREATE TABLE snakes (
    score_id SERIAL PRIMARY KEY,
    user_id INT NOT NULL
    score INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (user_id) REFERENCES users(id)
 );